export default function Swears(){
return {
 "africoon": 1,
 "anal": 1,
 "analannie": 1,
 "analsex": 1,
 "anus": 1,
 "arabush": 1,
 "arabushs": 1,
 "areola": 1,
 "argie": 1,
 "armo": 1,
 "armos": 1,
 "arse": 1,
 "arsehole": 1,
 "ass": 1,
 "assbagger": 1,
 "assblaster": 1,
 "assclown": 1,
 "asscowboy": 1,
 "asses": 1,
 "assfuck": 1,
 "assfucker": 1,
 "asshat": 1,
 "asshole": 1,
 "assholes": 1,
 "asshore": 1,
 "assjockey": 1,
 "asskiss": 1,
 "asskisser": 1,
 "assklown": 1,
 "asslick": 1,
 "asslicker": 1,
 "asslover": 1,
 "assman": 1,
 "assmonkey": 1,
 "assmunch": 1,
 "assmuncher": 1,
 "asspacker": 1,
 "asspirate": 1,
 "asspuppies": 1,
 "assranger": 1,
 "asswhore": 1,
 "asswipe": 1,
 "athletesfoot": 1,
 "badfuck": 1,
 "balllicker": 1,
 "balls": 1,
 "ballsack": 1,
 "banging": 1,
 "bastard": 1,
 "bazongas": 1,
 "bazooms": 1,
 "beatoff": 1,
 "beatyourmeat": 1,
 "biatch": 1,
 "bigass": 1,
 "bigbastard": 1,
 "bigbutt": 1,
 "bitch": 1,
 "bitcher": 1,
 "bitches": 1,
 "bitchez": 1,
 "bitchin": 1,
 "bitching": 1,
 "bitchslap": 1,
 "bitchy": 1,
 "biteme": 1,
 "blowjob": 1,
 "bluegum": 1,
 "bluegums": 1,
 "bohunk": 1,
 "bollick": 1,
 "bollock": 1,
 "bollocks": 1,
 "boner": 1,
 "bong": 1,
 "boob": 1,
 "boobies": 1,
 "boobs": 1,
 "booby": 1,
 "boong": 1,
 "boonga": 1,
 "boongas": 1,
 "boongs": 1,
 "boonie": 1,
 "boonies": 1,
 "bootlip": 1,
 "bootlips": 1,
 "booty": 1,
 "bootycall": 1,
 "bosche": 1,
 "bosches": 1,
 "boschs": 1,
 "bounty bar": 1,
 "bounty bars": 1,
 "bountybar": 1,
 "brea5t": 1,
 "breastjob": 1,
 "breastlover": 1,
 "breastman": 1,
 "brothel": 1,
 "buddhahead": 1,
 "buddhaheads": 1,
 "buffies": 1,
 "bugger": 1,
 "buggered": 1,
 "buggery": 1,
 "bule": 1,
 "bules": 1,
 "bullcrap": 1,
 "bulldike": 1,
 "bulldyke": 1,
 "bullshit": 1,
 "bumblefuck": 1,
 "bumfuck": 1,
 "bung": 1,
 "bunga": 1,
 "bungas": 1,
 "bunghole": 1,
 "burr head": 1,
 "burr heads": 1,
 "burrhead": 1,
 "burrheads": 1,
 "butchbabes": 1,
 "butchdike": 1,
 "butchdyke": 1,
 "buttbang": 1,
 "buttface": 1,
 "buttfuck": 1,
 "buttfucker": 1,
 "buttfuckers": 1,
 "butthead": 1,
 "buttman": 1,
 "buttmunch": 1,
 "buttmuncher": 1,
 "buttpirate": 1,
 "buttplug": 1,
 "buttstain": 1,
 "byatch": 1,
 "cacker": 1,
 "camel jockey": 1,
 "camel jockeys": 1,
 "cameljockey": 1,
 "cameltoe": 1,
 "carpetmuncher": 1,
 "carruth": 1,
 "chav": 1,
 "cherrypopper": 1,
 "chickslick": 1,
 "china swede": 1,
 "china swedes": 1,
 "chinaman": 1,
 "chinamen": 1,
 "chinaswede": 1,
 "chinaswedes": 1,
 "ching chong": 1,
 "ching chongs": 1,
 "chingchong": 1,
 "chingchongs": 1,
 "chink": 1,
 "chinks": 1,
 "chinky": 1,
 "choad": 1,
 "chode": 1,
 "chonkies": 1,
 "chonky": 1,
 "chonkys": 1,
 "christ killer": 1,
 "christ killers": 1,
 "chug": 1,
 "chugs": 1,
 "chunger": 1,
 "chungers": 1,
 "chunkies": 1,
 "chunky": 1,
 "chunkys": 1,
 "clamdigger": 1,
 "clamdiver": 1,
 "clansman": 1,
 "clansmen": 1,
 "clanswoman": 1,
 "clanswomen": 1,
 "clit": 1,
 "clitoris": 1,
 "clogwog": 1,
 "cocaine": 1,
 "cock": 1,
 "cockblock": 1,
 "cockblocker": 1,
 "cockcowboy": 1,
 "cockfight": 1,
 "cockhead": 1,
 "cockknob": 1,
 "cocklicker": 1,
 "cocklover": 1,
 "cocknob": 1,
 "cockqueen": 1,
 "cockrider": 1,
 "cocksman": 1,
 "cocksmith": 1,
 "cocksmoker": 1,
 "cocksucer": 1,
 "cocksuck": 1,
 "cocksucked": 1,
 "cocksucker": 1,
 "cocksucking": 1,
 "cocktease": 1,
 "cocky": 1,
 "cohee": 1,
 "coitus": 1,
 "coolie": 1,
 "coolies": 1,
 "cooly": 1,
 "coon": 1,
 "coon ass": 1,
 "coon asses": 1,
 "coonass": 1,
 "coonasses": 1,
 "coondog": 1,
 "coons": 1,
 "copulate": 1,
 "cornhole": 1,
 "crack": 1,
 "cracka": 1,
 "crackpipe": 1,
 "crackwhore": 1,
 "crapola": 1,
 "crapper": 1,
 "crappy": 1,
 "crotch": 1,
 "crotchjockey": 1,
 "crotchmonkey": 1,
 "crotchrot": 1,
 "cum": 1,
 "cumbubble": 1,
 "cumfest": 1,
 "cumjockey": 1,
 "cumm": 1,
 "cummer": 1,
 "cumming": 1,
 "cumquat": 1,
 "cumqueen": 1,
 "cumshot": 1,
 "cunilingus": 1,
 "cunillingus": 1,
 "cunn": 1,
 "cunnilingus": 1,
 "cunntt": 1,
 "cunt": 1,
 "cunteyed": 1,
 "cuntfuck": 1,
 "cuntfucker": 1,
 "cuntlick": 1,
 "cuntlicker": 1,
 "cuntlicking": 1,
 "cuntsucker": 1,
 "curry muncher": 1,
 "curry munchers": 1,
 "currymuncher": 1,
 "currymunchers": 1,
 "cushi": 1,
 "cushis": 1,
 "cybersex": 1,
 "cyberslimer": 1,
 "dago": 1,
 "dagos": 1,
 "dahmer": 1,
 "dammit": 1,
 "damn": 1,
 "damnation": 1,
 "damnit": 1,
 "darkey": 1,
 "darkeys": 1,
 "darkie": 1,
 "darkies": 1,
 "darky": 1,
 "datnigga": 1,
 "deapthroat": 1,
 "deepthroat": 1,
 "dego": 1,
 "degos": 1,
 "devil": 1,
 "devilworshipper": 1,
 "diaper head": 1,
 "diaper heads": 1,
 "diaperhead": 1,
 "diaperheads": 1,
 "dick": 1,
 "dickbrain": 1,
 "dickforbrains": 1,
 "dickhead": 1,
 "dickless": 1,
 "dicklick": 1,
 "dicklicker": 1,
 "dickman": 1,
 "dickwad": 1,
 "dickweed": 1,
 "diddle": 1,
 "dike": 1,
 "dildo": 1,
 "dingleberry": 1,
 "dink": 1,
 "dinks": 1,
 "dipshit": 1,
 "dipstick": 1,
 "dix": 1,
 "dixiedike": 1,
 "dixiedyke": 1,
 "doggiestyle": 1,
 "doggystyle": 1,
 "dong": 1,
 "doodoo": 1,
 "dope": 1,
 "dot head": 1,
 "dot heads": 1,
 "dothead": 1,
 "dotheads": 1,
 "dragqueen": 1,
 "dragqween": 1,
 "dripdick": 1,
 "dumbass": 1,
 "dumbbitch": 1,
 "dumbfuck": 1,
 "dune coon": 1,
 "dune coons": 1,
 "dyefly": 1,
 "dyke": 1,
 "easyslut": 1,
 "eatballs": 1,
 "eatme": 1,
 "eatpussy": 1,
 "eight ball": 1,
 "eight balls": 1,
 "ejaculate": 1,
 "ejaculated": 1,
 "ejaculating": 1,
 "ejaculation": 1,
 "enema": 1,
 "erect": 1,
 "erection": 1,
 "esqua": 1,
 "evl": 1,
 "excrement": 1,
 "exkwew": 1,
 "facefucker": 1,
 "faeces": 1,
 "fag": 1,
 "fagging": 1,
 "faggot": 1,
 "fagot": 1,
 "fannyfucker": 1,
 "fart": 1,
 "farted": 1,
 "farting": 1,
 "farty": 1,
 "fastfuck": 1,
 "fatah": 1,
 "fatass": 1,
 "fatfuck": 1,
 "fatfucker": 1,
 "fatso": 1,
 "fckcum": 1,
 "feces": 1,
 "felatio": 1,
 "felch": 1,
 "felcher": 1,
 "felching": 1,
 "fellatio": 1,
 "feltch": 1,
 "feltcher": 1,
 "feltching": 1,
 "fetish": 1,
 "fingerfood": 1,
 "fingerfuck": 1,
 "fingerfucked": 1,
 "fingerfucker": 1,
 "fingerfuckers": 1,
 "fingerfucking": 1,
 "fister": 1,
 "fistfuck": 1,
 "fistfucked": 1,
 "fistfucker": 1,
 "fistfucking": 1,
 "fisting": 1,
 "flange": 1,
 "flasher": 1,
 "flatulence": 1,
 "floo": 1,
 "flydie": 1,
 "flydye": 1,
 "fok": 1,
 "fondle": 1,
 "footaction": 1,
 "footfuck": 1,
 "footfucker": 1,
 "footlicker": 1,
 "footstar": 1,
 "foreskin": 1,
 "forni": 1,
 "fornicate": 1,
 "foursome": 1,
 "fourtwenty": 1,
 "freakfuck": 1,
 "freakyfucker": 1,
 "freefuck": 1,
 "fruitcake": 1,
 "fubar": 1,
 "fuck": 1,
 "fucka": 1,
 "fuckable": 1,
 "fuckbag": 1,
 "fuckbook": 1,
 "fuckbuddy": 1,
 "fucked": 1,
 "fuckedup": 1,
 "fucker": 1,
 "fuckers": 1,
 "fuckface": 1,
 "fuckfest": 1,
 "fuckfreak": 1,
 "fuckfriend": 1,
 "fuckhead": 1,
 "fuckin": 1,
 "fuckina": 1,
 "fucking": 1,
 "fuckingbitch": 1,
 "fuckinnuts": 1,
 "fuckinright": 1,
 "fuckit": 1,
 "fuckknob": 1,
 "fuckme": 1,
 "fuckmehard": 1,
 "fuckmonkey": 1,
 "fuckoff": 1,
 "fuckpig": 1,
 "fucks": 1,
 "fucktard": 1,
 "fuckwhore": 1,
 "fuckyou": 1,
 "fuck you": 1,
 "fudgepacker": 1,
 "fugly": 1,
 "fuk": 1,
 "fuks": 1,
 "funfuck": 1,
 "gable": 1,
 "gables": 1,
 "gangbang": 1,
 "gangbanged": 1,
 "gangbanger": 1,
 "gangsta": 1,
 "gator bait": 1,
 "gatorbait": 1,
 "gay": 1,
 "gays": 1,
 "gaymuthafuckinwhore": 1,
 "gaysex": 1,
 "geez": 1,
 "geezer": 1,
 "geni": 1,
 "genital": 1,
 "getiton": 1,
 "ginzo": 1,
 "ginzos": 1,
 "gipp": 1,
 "gippo": 1,
 "gippos": 1,
 "gipps": 1,
 "givehead": 1,
 "glazeddonut": 1,
 "gob": 1,
 "god": 1,
 "godammit": 1,
 "goddamit": 1,
 "goddammit": 1,
 "goddamn": 1,
 "goddamned": 1,
 "goddamnes": 1,
 "goddamnit": 1,
 "goddamnmuthafucker": 1,
 "goldenshower": 1,
 "golliwog": 1,
 "golliwogs": 1,
 "gonorrehea": 1,
 "gonzagas": 1,
 "gook": 1,
 "gook eye": 1,
 "gook eyes": 1,
 "gookeye": 1,
 "gookeyes": 1,
 "gookies": 1,
 "gooks": 1,
 "gooky": 1,
 "gora": 1,
 "goras": 1,
 "gotohell": 1,
 "goy": 1,
 "goyim": 1,
 "greaseball": 1,
 "greaseballs": 1,
 "greaser": 1,
 "greasers": 1,
 "gringo": 1,
 "gringos": 1,
 "groe": 1,
 "groid": 1,
 "groids": 1,
 "gross": 1,
 "grostulation": 1,
 "gub": 1,
 "gubba": 1,
 "gubbas": 1,
 "gubs": 1,
 "guinea": 1,
 "guineas": 1,
 "guizi": 1,
 "gummer": 1,
 "gwailo": 1,
 "gwailos": 1,
 "gweilo": 1,
 "gweilos": 1,
 "gyopo": 1,
 "gyopos": 1,
 "gyp": 1,
 "gyped": 1,
 "gypo": 1,
 "gypos": 1,
 "gypp": 1,
 "gypped": 1,
 "gyppie": 1,
 "gyppies": 1,
 "gyppo": 1,
 "gyppos": 1,
 "gyppy": 1,
 "gyppys": 1,
 "gypsies": 1,
 "gypsy": 1,
 "gypsys": 1,
 "hadji": 1,
 "hadjis": 1,
 "hairyback": 1,
 "hairybacks": 1,
 "haji": 1,
 "hajis": 1,
 "hajji": 1,
 "hajjis": 1,
 "half breed": 1,
 "half caste": 1,
 "halfbreed": 1,
 "halfcaste": 1,
 "hamas": 1,
 "handjob": 1,
 "haole": 1,
 "haoles": 1,
 "hapa": 1,
 "hardon": 1,
 "headfuck": 1,
 "hebe": 1,
 "hebephila": 1,
 "hebephile": 1,
 "hebephiles": 1,
 "hebephilia": 1,
 "hebephilic": 1,
 "hebes": 1,
 "heeb": 1,
 "heebs": 1,
 "heroin": 1,
 "herpes": 1,
 "hillbillies": 1,
 "hillbilly": 1,
 "hindoo": 1,
 "hiscock": 1,
 "hitler": 1,
 "hitlerism": 1,
 "hitlerist": 1,
 "hiv": 1,
 "hobo": 1,
 "hodgie": 1,
 "hoes": 1,
 "holestuffer": 1,
 "homicide": 1,
 "homo": 1,
 "homobangers": 1,
 "homosexual": 1,
 "honger": 1,
 "honkers": 1,
 "honkey": 1,
 "honkeys": 1,
 "honkie": 1,
 "honkies": 1,
 "honky": 1,
 "hooker": 1,
 "hookers": 1,
 "hooters": 1,
 "hore": 1,
 "hori": 1,
 "horis": 1,
 "hork": 1,
 "horney": 1,
 "horniest": 1,
 "horny": 1,
 "horseshit": 1,
 "hosejob": 1,
 "hoser": 1,
 "hotdamn": 1,
 "hotpussy": 1,
 "hottotrot": 1,
 "hussy": 1,
 "hymen": 1,
 "hymie": 1,
 "hymies": 1,
 "iblowu": 1,
 "idiot": 1,
 "ike": 1,
 "ikes": 1,
 "ikey": 1,
 "ikeymo": 1,
 "ikeymos": 1,
 "ikwe": 1,
 "illegals": 1,
 "incest": 1,
 "indon": 1,
 "indons": 1,
 "injun": 1,
 "injuns": 1,
 "insest": 1,
 "intercourse": 1,
 "interracial": 1,
 "intheass": 1,
 "inthebuff": 1,
 "italiano": 1,
 "jackass": 1,
 "jackoff": 1,
 "jackshit": 1,
 "jacktheripper": 1,
 "jap": 1,
 "japcrap": 1,
 "japie": 1,
 "japies": 1,
 "japs": 1,
 "jebus": 1,
 "jeez": 1,
 "jerkoff": 1,
 "jerries": 1,
 "jesus": 1,
 "jesuschrist": 1,
 "jewed": 1,
 "jewess": 1,
 "jig": 1,
 "jiga": 1,
 "jigaboo": 1,
 "jigaboos": 1,
 "jigarooni": 1,
 "jigaroonis": 1,
 "jigg": 1,
 "jigga": 1,
 "jiggabo": 1,
 "jiggabos": 1,
 "jiggas": 1,
 "jigger": 1,
 "jiggers": 1,
 "jiggs": 1,
 "jiggy": 1,
 "jigs": 1,
 "jihad": 1,
 "jijjiboo": 1,
 "jijjiboos": 1,
 "jimfish": 1,
 "jism": 1,
 "jiz": 1,
 "jizim": 1,
 "jizjuice": 1,
 "jizm": 1,
 "jizz": 1,
 "jizzim": 1,
 "jizzum": 1,
 "juggalo": 1,
 "jungle bunnies": 1,
 "jungle bunny": 1,
 "junglebunny": 1,
 "kacap": 1,
 "kacapas": 1,
 "kacaps": 1,
 "kaffer": 1,
 "kaffir": 1,
 "kaffre": 1,
 "kafir": 1,
 "kanake": 1,
 "katsap": 1,
 "katsaps": 1,
 "khokhol": 1,
 "khokhols": 1,
 "kigger": 1,
 "kike": 1,
 "kikes": 1,
 "kimchis": 1,
 "kink": 1,
 "kinky": 1,
 "kissass": 1,
 "kkk": 1,
 "klansman": 1,
 "klansmen": 1,
 "klanswoman": 1,
 "klanswomen": 1,
 "knockers": 1,
 "kock": 1,
 "kondum": 1,
 "kotex": 1,
 "krap": 1,
 "krappy": 1,
 "kraut": 1,
 "krauts": 1,
 "kuffar": 1,
 "kum": 1,
 "kumbubble": 1,
 "kumbullbe": 1,
 "kummer": 1,
 "kumming": 1,
 "kumquat": 1,
 "kums": 1,
 "kunilingus": 1,
 "kunnilingus": 1,
 "kunt": 1,
 "kushi": 1,
 "kushis": 1,
 "kwa": 1,
 "kwai lo": 1,
 "kwai los": 1,
 "ky": 1,
 "kyke": 1,
 "kykes": 1,
 "kyopo": 1,
 "kyopos": 1,
 "lactate": 1,
 "lapdance": 1,
 "lebo": 1,
 "lebos": 1,
 "lesbain": 1,
 "lesbayn": 1,
 "lesbian": 1,
 "lesbin": 1,
 "lesbo": 1,
 "lez": 1,
 "lezbe": 1,
 "lezbefriends": 1,
 "lezbo": 1,
 "lezz": 1,
 "lezzo": 1,
 "libido": 1,
 "licker": 1,
 "lickme": 1,
 "limey": 1,
 "limpdick": 1,
 "limy": 1,
 "liquor": 1,
 "livesex": 1,
 "loadedgun": 1,
 "lovebone": 1,
 "lovegoo": 1,
 "lovegun": 1,
 "lovejuice": 1,
 "lovemuscle": 1,
 "lovepistol": 1,
 "loverocket": 1,
 "lowlife": 1,
 "lsd": 1,
 "lubejob": 1,
 "lubra": 1,
 "luckycammeltoe": 1,
 "lugan": 1,
 "lugans": 1,
 "lynch": 1,
 "mabuno": 1,
 "mabunos": 1,
 "macaca": 1,
 "macacas": 1,
 "mafia": 1,
 "magicwand": 1,
 "mahbuno": 1,
 "mahbunos": 1,
 "mams": 1,
 "manhater": 1,
 "manpaste": 1,
 "marijuana": 1,
 "mastabate": 1,
 "mastabater": 1,
 "masterbate": 1,
 "masterblaster": 1,
 "mastrabator": 1,
 "masturbate": 1,
 "masturbating": 1,
 "mattressprincess": 1,
 "mau mau": 1,
 "mau maus": 1,
 "maumau": 1,
 "maumaus": 1,
 "meatbeatter": 1,
 "meatrack": 1,
 "meth": 1,
 "mgger": 1,
 "mggor": 1,
 "mickeyfinn": 1,
 "milf": 1,
 "mockey": 1,
 "mockie": 1,
 "mocky": 1,
 "mofo": 1,
 "moky": 1,
 "molest": 1,
 "molestation": 1,
 "molester": 1,
 "molestor": 1,
 "moneyshot": 1,
 "moon cricket": 1,
 "moon crickets": 1,
 "mooncricket": 1,
 "mooncrickets": 1,
 "moron": 1,
 "moskal": 1,
 "moskals": 1,
 "moslem": 1,
 "mosshead": 1,
 "mothafuck": 1,
 "mothafucka": 1,
 "mothafuckaz": 1,
 "mothafucked": 1,
 "mothafucker": 1,
 "mothafuckin": 1,
 "mothafucking": 1,
 "mothafuckings": 1,
 "motherfuck": 1,
 "motherfucked": 1,
 "motherfucker": 1,
 "motherfuckin": 1,
 "motherfucking": 1,
 "motherfuckings": 1,
 "motherlovebone": 1,
 "muff": 1,
 "muffdive": 1,
 "muffdiver": 1,
 "muffindiver": 1,
 "mufflikcer": 1,
 "mulatto": 1,
 "muncher": 1,
 "munt": 1,
 "mzungu": 1,
 "mzungus": 1,
 "narcotic": 1,
 "nastybitch": 1,
 "nastyho": 1,
 "nastyslut": 1,
 "nastywhore": 1,
 "nazi": 1,
 "necro": 1,
 "negres": 1,
 "negress": 1,
 "negro": 1,
 "negroes": 1,
 "negroid": 1,
 "negros": 1,
 "nig": 1,
 "nigar": 1,
 "nigars": 1,
 "nigerian": 1,
 "nigerians": 1,
 "nigers": 1,
 "nigette": 1,
 "nigettes": 1,
 "nigg": 1,
 "nigga": 1,
 "niggah": 1,
 "niggahs": 1,
 "niggar": 1,
 "niggaracci": 1,
 "niggard": 1,
 "niggarded": 1,
 "niggarding": 1,
 "niggardliness": 1,
 "niggardlinesss": 1,
 "niggards": 1,
 "niggars": 1,
 "niggas": 1,
 "niggaz": 1,
 "nigger": 1,
 "niggerhead": 1,
 "niggerhole": 1,
 "niggers": 1,
 "niggle": 1,
 "niggled": 1,
 "niggles": 1,
 "niggling": 1,
 "nigglings": 1,
 "niggor": 1,
 "niggress": 1,
 "niggresses": 1,
 "nigguh": 1,
 "nigguhs": 1,
 "niggur": 1,
 "niggurs": 1,
 "niglet": 1,
 "nignog": 1,
 "nigor": 1,
 "nigors": 1,
 "nigr": 1,
 "nigra": 1,
 "nigras": 1,
 "nigre": 1,
 "nigres": 1,
 "nigress": 1,
 "nigs": 1,
 "nip": 1,
 "nipple": 1,
 "nipplering": 1,
 "nittit": 1,
 "nlgger": 1,
 "nlggor": 1,
 "nofuckingway": 1,
 "nook": 1,
 "nookey": 1,
 "nookie": 1,
 "noonan": 1,
 "nooner": 1,
 "nude": 1,
 "nudger": 1,
 "nuke": 1,
 "nutfucker": 1,
 "nymph": 1,
 "ontherag": 1,
 "oral": 1,
 "orga": 1,
 "orgasim": 1,
 "orgasm": 1,
 "orgies": 1,
 "orgy": 1,
 "paddy": 1,
 "paederastic": 1,
 "paederasts": 1,
 "paederasty": 1,
 "paki": 1,
 "pakis": 1,
 "palesimian": 1,
 "pancake face": 1,
 "pancake faces": 1,
 "pansies": 1,
 "pansy": 1,
 "panti": 1,
 "panties": 1,
 "payo": 1,
 "pearlnecklace": 1,
 "peck": 1,
 "pecker": 1,
 "peckerwood": 1,
 "pederastic": 1,
 "pederasts": 1,
 "pederasty": 1,
 "pedo": 1,
 "pedophile": 1,
 "pedophiles": 1,
 "pedophilia": 1,
 "pedophilic": 1,
 "pee": 1,
 "peehole": 1,
 "peepee": 1,
 "peepshow": 1,
 "peepshpw": 1,
 "pendy": 1,
 "penetration": 1,
 "peni5": 1,
 "penile": 1,
 "penis": 1,
 "penises": 1,
 "perv": 1,
 "phonesex": 1,
 "phuk": 1,
 "phuked": 1,
 "phuking": 1,
 "phukked": 1,
 "phukking": 1,
 "phungky": 1,
 "phuq": 1,
 "pi55": 1,
 "picaninny": 1,
 "piccaninny": 1,
 "pickaninnies": 1,
 "pickaninny": 1,
 "piefke": 1,
 "piefkes": 1,
 "piker": 1,
 "pikey": 1,
 "piky": 1,
 "pimp": 1,
 "pimped": 1,
 "pimper": 1,
 "pimpjuic": 1,
 "pimpjuice": 1,
 "pimpsimp": 1,
 "pindick": 1,
 "piss": 1,
 "pissed": 1,
 "pisser": 1,
 "pisses": 1,
 "pisshead": 1,
 "pissin": 1,
 "pissing": 1,
 "pissoff": 1,
 "playboy": 1,
 "playgirl": 1,
 "pocha": 1,
 "pochas": 1,
 "pocho": 1,
 "pochos": 1,
 "pocketpool": 1,
 "pohm": 1,
 "pohms": 1,
 "polack": 1,
 "polacks": 1,
 "pollock": 1,
 "pollocks": 1,
 "pom": 1,
 "pommie": 1,
 "pommie grant": 1,
 "pommie grants": 1,
 "pommies": 1,
 "pommy": 1,
 "poms": 1,
 "poo": 1,
 "poon": 1,
 "poontang": 1,
 "popimp": 1,
 "porch monkey": 1,
 "porch monkies": 1,
 "porchmonkey": 1,
 "porn": 1,
 "pornflick": 1,
 "pornking": 1,
 "porno": 1,
 "pornography": 1,
 "pornprincess": 1,
 "prairie nigger": 1,
 "prairie niggers": 1,
 "pric": 1,
 "prick": 1,
 "prickhead": 1,
 "prostitute": 1,
 "protestant": 1,
 "pube": 1,
 "pubic": 1,
 "pubiclice": 1,
 "pud": 1,
 "pudboy": 1,
 "pudd": 1,
 "puddboy": 1,
 "puke": 1,
 "puntang": 1,
 "purinapricness": 1,
 "puss": 1,
 "pussie": 1,
 "pussies": 1,
 "pussy": 1,
 "pussycat": 1,
 "pussyeater": 1,
 "pussyfucker": 1,
 "pussylicker": 1,
 "pussylips": 1,
 "pussylover": 1,
 "pussypounder": 1,
 "pusy": 1,
 "quashie": 1,
 "queef": 1,
 "queer": 1,
 "quickie": 1,
 "quim": 1,
 "ra8s": 1,
 "racist": 1,
 "radical": 1,
 "radicals": 1,
 "raghead": 1,
 "ragheads": 1,
 "randy": 1,
 "rape": 1,
 "raped": 1,
 "raper": 1,
 "rapist": 1,
 "rearend": 1,
 "rearentry": 1,
 "rectum": 1,
 "redleg": 1,
 "redlegs": 1,
 "redneck": 1,
 "rednecks": 1,
 "redskin": 1,
 "redskins": 1,
 "reefer": 1,
 "reestie": 1,
 "rentafuck": 1,
 "rere": 1,
 "retard": 1,
 "retarded": 1,
 "ribbed": 1,
 "rigger": 1,
 "rimjob": 1,
 "rimming": 1,
 "round eyes": 1,
 "roundeye": 1,
 "russki": 1,
 "russkie": 1,
 "sadis": 1,
 "sadom": 1,
 "sambo": 1,
 "sambos": 1,
 "samckdaddy": 1,
 "sand nigger": 1,
 "sand niggers": 1,
 "sandm": 1,
 "sandnigger": 1,
 "satan": 1,
 "scag": 1,
 "scallywag": 1,
 "scat": 1,
 "schlong": 1,
 "schvartse": 1,
 "schvartsen": 1,
 "schwartze": 1,
 "schwartzen": 1,
 "screw": 1,
 "screwyou": 1,
 "scrotum": 1,
 "scum": 1,
 "semen": 1,
 "sex": 1,
 "sexed": 1,
 "sexfarm": 1,
 "sexhound": 1,
 "sexhouse": 1,
 "sexing": 1,
 "sexkitten": 1,
 "sexpot": 1,
 "sexslave": 1,
 "sextogo": 1,
 "sextoy": 1,
 "sextoys": 1,
 "sexual": 1,
 "sexually": 1,
 "sexwhore": 1,
 "sexy": 1,
 "sexymoma": 1,
 "sexyslim": 1,
 "shag": 1,
 "shaggin": 1,
 "shagging": 1,
 "shav": 1,
 "shawtypimp": 1,
 "sheeney": 1,
 "shinola": 1,
 "shit": 1,
 "shitcan": 1,
 "shitdick": 1,
 "shite": 1,
 "shiteater": 1,
 "shited": 1,
 "shitface": 1,
 "shitfaced": 1,
 "shitfit": 1,
 "shitforbrains": 1,
 "shitfuck": 1,
 "shitfucker": 1,
 "shitfull": 1,
 "shithapens": 1,
 "shithappens": 1,
 "shithead": 1,
 "shithouse": 1,
 "shiting": 1,
 "shitlist": 1,
 "shitola": 1,
 "shitoutofluck": 1,
 "shits": 1,
 "shitstain": 1,
 "shitted": 1,
 "shitter": 1,
 "shitting": 1,
 "shitty": 1,
 "shortfuck": 1,
 "shylock": 1,
 "shylocks": 1,
 "sissy": 1,
 "sixsixsix": 1,
 "sixtynine": 1,
 "sixtyniner": 1,
 "skank": 1,
 "skankbitch": 1,
 "skankfuck": 1,
 "skankwhore": 1,
 "skanky": 1,
 "skankybitch": 1,
 "skankywhore": 1,
 "skinflute": 1,
 "skum": 1,
 "skumbag": 1,
 "skwa": 1,
 "slanteye": 1,
 "slanty": 1,
 "slapper": 1,
 "slaughter": 1,
 "slav": 1,
 "slave": 1,
 "slavedriver": 1,
 "sleezebag": 1,
 "sleezeball": 1,
 "slideitin": 1,
 "slimeball": 1,
 "slimebucket": 1,
 "slopehead": 1,
 "slopeheads": 1,
 "sloper": 1,
 "slopers": 1,
 "slopey": 1,
 "slopeys": 1,
 "slopies": 1,
 "slopy": 1,
 "slut": 1,
 "sluts": 1,
 "slutt": 1,
 "slutting": 1,
 "slutty": 1,
 "slutwear": 1,
 "slutwhore": 1,
 "smack": 1,
 "smackthemonkey": 1,
 "smut": 1,
 "snatch": 1,
 "snatchpatch": 1,
 "sniggers": 1,
 "snowback": 1,
 "snownigger": 1,
 "sodom": 1,
 "sodomise": 1,
 "sodomite": 1,
 "sodomize": 1,
 "sodomy": 1,
 "sonofabitch": 1,
 "sonofbitch": 1,
 "sooties": 1,
 "sooty": 1,
 "spade": 1,
 "spades": 1,
 "spaghettibender": 1,
 "spaghettinigger": 1,
 "spank": 1,
 "spankthemonkey": 1,
 "spearchucker": 1,
 "spearchuckers": 1,
 "sperm": 1,
 "spermacide": 1,
 "spermbag": 1,
 "spermhearder": 1,
 "spermherder": 1,
 "spic": 1,
 "spick": 1,
 "spicks": 1,
 "spics": 1,
 "spig": 1,
 "spigotty": 1,
 "spik": 1,
 "spit": 1,
 "spitter": 1,
 "splittail": 1,
 "spooge": 1,
 "spreadeagle": 1,
 "spunk": 1,
 "spunky": 1,
 "sqeh": 1,
 "squa": 1,
 "squarehead": 1,
 "squareheads": 1,
 "squaw": 1,
 "squinty": 1,
 "stagg": 1,
 "stiffy": 1,
 "strapon": 1,
 "stringer": 1,
 "stripclub": 1,
 "stroking": 1,
 "stuinties": 1,
 "stupid": 1,
 "stupidfuck": 1,
 "stupidfucker": 1,
 "suckdick": 1,
 "sucker": 1,
 "suckme": 1,
 "suckmyass": 1,
 "suckmydick": 1,
 "suckmytit": 1,
 "suckoff": 1,
 "suicide": 1,
 "swallow": 1,
 "swallower": 1,
 "swalow": 1,
 "swamp guinea": 1,
 "swamp guineas": 1,
 "swastika": 1,
 "syphilis": 1,
 "tacohead": 1,
 "tacoheads": 1,
 "taff": 1,
 "tang": 1,
 "tantra": 1,
 "tar babies": 1,
 "tar baby": 1,
 "tarbaby": 1,
 "tard": 1,
 "teat": 1,
 "terrorist": 1,
 "teste": 1,
 "testicle": 1,
 "testicles": 1,
 "thicklip": 1,
 "thicklips": 1,
 "thirdeye": 1,
 "thirdleg": 1,
 "threesome": 1,
 "threeway": 1,
 "timber nigger": 1,
 "timber niggers": 1,
 "timbernigger": 1,
 "tinker": 1,
 "tinkers": 1,
 "tinkle": 1,
 "tit": 1,
 "titbitnipply": 1,
 "titfuck": 1,
 "titfucker": 1,
 "titfuckin": 1,
 "titjob": 1,
 "titlicker": 1,
 "titlover": 1,
 "tits": 1,
 "tittie": 1,
 "titties": 1,
 "titty": 1,
 "tnt": 1,
 "tongethruster": 1,
 "tonguethrust": 1,
 "tonguetramp": 1,
 "torture": 1,
 "tosser": 1,
 "towel head": 1,
 "towel heads": 1,
 "towelhead": 1,
 "trailertrash": 1,
 "tramp": 1,
 "trannie": 1,
 "tranny": 1,
 "transvestite": 1,
 "triplex": 1,
 "trisexual": 1,
 "hoe": 1,
 "trots": 1,
 "tuckahoe": 1,
 "tunneloflove": 1,
 "turd": 1,
 "turnon": 1,
 "twat": 1,
 "twink": 1,
 "twinkie": 1,
 "twobitwhore": 1,
 "ukrop": 1,
 "uncle tom": 1,
 "unfuckable": 1,
 "upskirt": 1,
 "uptheass": 1,
 "upthebutt": 1,
 "usama": 1,
 "uterus": 1,
 "vagina": 1,
 "vaginal": 1,
 "vibr": 1,
 "vibrater": 1,
 "vibrator": 1,
 "virginbreaker": 1,
 "vomit": 1,
 "vulva": 1,
 "wab": 1,
 "wank": 1,
 "wanker": 1,
 "wanking": 1,
 "waysted": 1,
 "weenie": 1,
 "weewee": 1,
 "welcher": 1,
 "welfare": 1,
 "wetb": 1,
 "wetback": 1,
 "wetbacks": 1,
 "wetspot": 1,
 "whacker": 1,
 "whash": 1,
 "whigger": 1,
 "whiggers": 1,
 "whiskeydick": 1,
 "whiskydick": 1,
 "whit": 1,
 "white trash": 1,
 "whitenigger": 1,
 "whites": 1,
 "whitetrash": 1,
 "whitey": 1,
 "whiteys": 1,
 "whities": 1,
 "whiz": 1,
 "whop": 1,
 "whore": 1,
 "whorefucker": 1,
 "whorehouse": 1,
 "wigga": 1,
 "wiggas": 1,
 "wigger": 1,
 "wiggers": 1,
 "willie": 1,
 "williewanker": 1,
 "willy": 1,
 "wn": 1,
 "wog": 1,
 "wogs": 1,
 "wop": 1,
 "wuss": 1,
 "wuzzie": 1,
 "yank": 1,
 "yankee": 1,
 "yankees": 1,
 "yanks": 1,
 "yarpie": 1,
 "yarpies": 1,
 "yellowman": 1,
 "yid": 1,
 "yids": 1,
 "zigabo": 1,
 "zigabos": 1,
 "zipperhead": 1,
 "zipperheads": 1,
 "fuckery": 1,
 "son of a": 1,
 "1 girls 1 cup": 1,
 "auto erotic": 1,
 "autoerotic": 1,
 "bimbo": 1,
 "bimbos": 1,
 "blue waffle": 1,
 "booty call": 1,
 "brown shower": 1,
 "brown showers": 1,
 "bukake": 1,
 "bukkake": 1,
 "bull shit": 1,
 "cocks": 1,
 "cow girl": 1,
 "cow girls": 1,
 "cowgirl": 1,
 "cowgirls": 1,
 "cuming": 1,
 "deep throat": 1,
 "dog style": 1,
 "doggie style": 1,
 "doggy style": 1,
 "erotic": 1,
 "erotism": 1,
 "femdom": 1,
 "fingering": 1,
 "footjob": 1,
 "foot job": 1,
 "futanari": 1,
 "futanary": 1,
 "gang bang": 1,
 "golden shower": 1,
 "hand job": 1,
 "jerk off": 1,
 "kinbaku": 1,
 "nipples": 1,
 "nudes": 1,
 "raping": 1,
 "sadism": 1,
 "shemale": 1,
 "she male": 1,
 "shibari": 1,
 "shibary": 1,
 "shota": 1,
 "smegma": 1,
 "strip club": 1,
 "sucks": 1,
 "three some": 1,
 "throating": 1,
 "yaoi": 1,
 "yury": 1,
 "airhead":1,
 "bonehead":1,
 "douche":1,
 "perver":1,
 "pussi":1,
 "you tard":1,
 "wack off":1,
 "bog off":1,
 "crap":1,
 "fat ass":1,
 "jerk":1,
 "minger":1,
 "nutsack":1,
 "pain in the ass":1,
 "piece of shit":1,
 "piss off":1,
 "schmuck":1,
 "screw up":1,
 "shmuck":1,
 "slag":1,
 "smart-arse":1,
 "smart-ass":1,
 "son of a bitch":1,
 "suckass":1,
 "tight-arse":1,
 "tight-ass":1,
 "extremetech.com":1,
 "chacha.com":1,
 "freemathhelp.com":1,
 "webmath.com":1,
 "mathway.com":1,
 "bbc.co.uk":1,
 "m.theartstory.org":1,
 "wiki.answers.com":1,
 "healthyheart.nhs.uk":1,
 "thefreedictionary.com":1,
 "pbs.org":1,
 "tricksmate.com":1,
 "onlinestatbook.com":1,
 "en.wikipedia.org":1,
 "real-world-physics-problems.com":1,
 "lordsandladies.org":1,
 "clickandlearn.cc":1,
 "webpages.uidaho.edu":1,
 "aryasamaj.com":1,
 "vark-learn.com":1,
 "linux.about.com":1,
 "readwritethink.org":1,
 "sparknotes.com":1,
 "alphabetize.org":1,
 "penpals.web.unc.edu":1,
 "translate.google.ca":1,
 "t.answers.com":1,
 "dictionary.reference.com":1,
 "rhythm-india.com":1,
 "mintaka.sdsu.edu":1,
 "nationalgeographic.com":1,
 "mathsisfun.com":1,
 "edublogs.org":1,
 "blogspot.co":1,
 "algebra.com":1,
 "delaware.gov":1,
 "easybib.com":1,
 "pullman.co.uk":1,
 "thenest.com":1,
 "buyessays.us":1,
 "tqn.com":1,
 "titanpad":1,
 "titanpad.com":1,
 "www.titanpad.com":1,
 "c1ck":1,
 "h@andjob":1,
 "handj1b":1,
 "h@andj1b":1,
 "fu.ck":1,
 "puss.y":1,
 "fuc.k":1,
 "f.uck":1,
 "p.ussy":1,
 "pu.ssy":1,
 "pus.sy":1,
 "f.u.c.k":1,
 "p.u.s.s.y":1,
 "send nudes":1,
 "sslut":1,
 "niqqa":1,
 "azz":1,
 "bich":1,
 "biach":1,
 "dumass":1,
 "stfu":1,
 "fuqq":1,
 "fuq":1,
 "crip":1,
 "dikk":1,
 "wtf":1,
 "nigg3r":1,
 "fricken":1,
 "asf":1,
 "faggt":1,
 "as f":1,
 "b*tch":1,
 "b i t c h":1,
 "n!gg3r":1,
 "dumb4zz":1,
 "idfc":1,
 "lmfao":1,
 "niga":1,
 "w hore":1,
 "b.tch":1,
 "d i c k":1,
 "fboy":1,
 "fgirl":1,
 "b1tch":1,
 "fck":1,
 "fu**":1,
 "ho*":1,
 "ho":1,
 "beyotch":1,
 "fukboi":1,
 "4ss":1,
 "wwhore":1,
 "r e t a r d":1,
 "f==k":1,
 "butthurt":1,
 "f off":1,
 "dicc":1,
 "lick you":1,
 "f a g g e t":1,
 "fagget":1,
 "d!ck":1,
 "n!gger":1,
 "buttsex":1,
 "wh ore":1,
 "sl ut":1,
 "bish":1,
 "thot":1,
 "fuc k":1,
 "a s s":1,
 "c.unt":1,
 "c u n t":1,
 "bit ch":1,
 "fack":1,
 "fu#ck":1,
 "sh it":1,
 "cr!p":1,
 "h orny":1,
 "nicca":1,
 "fukk":1,
 "nig ga":1,
 "f##k":1,
 "mathway":1,
 "smd":1,
 "a55":1,
 "bxtches":1,
 "a**hole":1,
 "give me head":1,
 "naked photos":1,
 "a queer":1,
 "fucKed":1,
 "fuvk":1,
 "bitc*":1,
 "dezz nuts":1,
 "d e e z n u t s":1,
 "cu m":1,
 "bihh":1,
 "f*k":1,
 "c*unt":1,
 "c***":1,
 "c**t":1,
 "sh*t":1,
 "female dog":1,
 "f******":1,
 "f*****g":1,
 "f***ing":1,
 "d***":1,
 "your butt":1,
 "j.erk":1,
 "f a g g o t":1,
 "bdsm":1,
 "kick your ass":1,
 "have s e x":1,
 "f u c k":1,
 "sthu":1,
 "cuum":1,
 "c.u.n.t":1,
 "f-u-c-k":1,
 "k y s":1,
 "negger":1,
 "n.igg":1,
 "n i g g":1,
 "niqq":1,
 "biitch":1,
 "s.hit":1,
 "cu.nt":1,
 "paedo":1,
 "a..ss":1,
 "http://zzz.totmania.net":1,
 "hoee":1,
 "fvck":1,
 "dick head":1,
 "blow job":1,
 "nagger":1,
 "shiz":1,
 "motherflutter":1,
 "fuc":1,
 "motherfuc":1,
 "t i t t i e s":1,
 "t i t t y":1,
 "b.i.t.c.h":1,
 "bi tch":1,
 "f/uck":1,
 "fu/ck":1,
 "fuc/k":1,
 "d/ick":1,
 "di/ck":1,
 "dic/k":1,
 "s/hit":1,
 "sh/it":1,
 "shi/t":1,
 "tiddy":1,
 "t1tt":1,
 "my balls":1,
 "your balls":1,
 "my penis":1,
 "your penis":1,
 "f..uck":1,
 "fucc":1,
 "btch":1,
 "f’uck":1,
 "f’ag":1,
 "@ss":1,
 "faygit":1,
 "hentai":1,
 "henta1":1,
 "suck cok":1,
 "my cok":1,
 "n!gg":1,
 "screw you":1,
 "sex with me":1,
 "lick my":1,
 "my dong":1,
 "google hangout":1,
 "pu$y":1,
 "pu$":1,
 "a$$":1,
 "h1e":1,
 "ƒuck":1,
 "niqa":1,
 "$hit":1,
 "fxx":1,
 "w.t.f":1,
 "but hole":1,
 "cvnt":1,
 "f,ck":1,
 "f*ck":1,
 "w.h.o.r.e":1,
 "batshit":1,
 "dik":1,
 "vegina":1,
 "my dick":1,
 "your dick":1,
 "ur dick":1,
 "tw@t":1,
 "my vagina":1,
 "your vagina":1,
 "your puss":1,
 "my puss":1,
 "pu55y":1,
 "friggin":1,
 "thong":1,
 "#ERROR!":1,
 "succ":1,
 "stripper":1,
 "dushbag":1,
 "midget":1,
 "fcuk":1,
 "bicth":1,
 "p/ussy":1,
 "pu/ssy":1,
 "pus/sy":1,
 "puss/y":1,
 "your snatch":1,
 "ur snatch":1,
 "her snatch":1,
 "her vagina":1,
 "his dick":1,
 "https://yadi.sk/":1,
 "puta":1,
 "vag":1,
 "math way":1,
 "beat meat":1,
 "beat my meat":1,
 "beat his meat":1,
 "cummies":1,
 "af":1,
 "shoot illegal":1,
 "kill ni":1,
 "kill illegal":1,
 "tallywacker":1,
 "Fuck":1,
 "Cunt":1,
 "Bitch":1,
 "Shit":1,
 "Nigg":1,
 "Fag":1,
 "nuds":1,
 "fuc*":1,
 "drink some bleach":1,
 "drink bleach":1,
 "fuuck":1,
 "Puss":1,
 "sl-ut":1,
 "f-uck":1,
 "f**k":1,
 "f you":1,
 "f that":1,
 "f$ck":1,
 "finger me":1,
 "finger you":1,
 "finger her":1,
 "pen1s":1,
 "fиck":1,
 "suck my":1,
 "fml":1,
 "deez nuts":1,
 "deez nutz":1,
 "my nuts":1,
 "n!99":1,
 "sh!t":1,
 "n199":1,
 "n1gg":1,
 "ni99":1,
 "sht":1,
 "my ig":1,
 "ig @":1,
 "my snap":1,
 "snap @":1,
 "insta @":1,
 "instagram @":1,
 "weiner":1,
 "pwussy":1,
 "your pushy":1,
 "puthy":1,
 "suck me":1,
 "TITS":1,
 "screw u":1,
 "ɴɪɢɢᴇʀ":1,
 "dipsh**":1,
 "sh**":1,
 "f-u-k":1,
 "bichth":1,
 "igger":1,
 "1gger":1,
 "peeranswer":1,
 "nibba":1,
 "b!tch":1,
 "soundcloud":1,
 "snapchat":1,
 "black lives don't matter":1,
 "redpill":1,
 "@gmail":1,
 "@yahoo":1,
 "@outlook":1,
 "ᴘᴜssʏ":1,
 "ᴀss":1,
 "ʙɪᴛᴄʜ":1,
 "sɴɪᴛᴄʜ":1,
 "ᴛʜᴏᴛ":1,
 "ғᴜᴄᴋɪɴɢ":1,
 "ғ":1,
 "biotch":1,
 "bit.ly":1,
 "a tard":1,
 "ujeb.se":1,
 "bit.do":1,
 "bööb":1,
 "hyperurl.co":1,
 "possy":1,
 "A > S > S":1,
 "A < S < S":1,
 "discord.gg":1,
 "smartass":1,
 "fuxk":1,
 "lmao":1,
 "lmaoo":1,
 "fxck":1,
 "kys":1,
 "kms":1,
 "kill yourself":1,
 "kill myself":1,
 "omfg":1,
 "axxhole":1,
 "p1rn":1,
 "1rgy":1,
 "tbfh":1,
 "facebook":1,
 "gmail":1,
 "Odysseyware":1,
 "titts":1,
 "大":1,
 "Live 1118":1,
 "办美":1,
 "415665716":1,
 "319777586":1,
 "861811713":1,
 "717191118":1,
 "blogspot":1,
 "liveonhd":1,
 "deadass":1,
 "blyat":1,
 ".jpg":1,
 ".png":1,
 "vstvon":1,
 ".de":1,
 "wimbledonpc":1,
 "Live®":1,
 "francevs":1,
 "supplierbin":1,
 "livegfootball":1,
 "funckin":1,
 "tourfrancede":1,
 "liveifootball":1,
 "britishopen":1,
 ".icu":1,
 "livetowatch":1,
 "lionsvs":1,
 "youtube":1,
 "youtube.com":1,
 "https://www.greatlovespells.co.uk":1,
 "greatlovespells":1,
 "whatsapp":1,
 "Watch WWE Smackdown":1,
 "mazda-ottawa":1,
 ".ncwit.":1,
 "buddypress.org":1,
 ".richlandsource.":1,
 "kansas-vs-michigan":1,
 ".okdrs.":1,
 "opengameart.org":1,
 "thephillyegotist.":1,
 "thewellproject.":1,
 "-vs-":1,
 ".reddit.":1,
 ".eu/":1,
 "live-":1,
 "/files/":1,
 "watch-":1,
 "grey-cuplive":1,
 "archiveofourown.org":1,
 "opengameart":1,
 "-full-":1,
 "reddit.":1,
 "DTF":1,
 "tf":1,
 "f***":1,
 "GTH":1,
 "w.tf":1,
 "w.th":1,
 "wt_f":1,
 "vagona":1,
 "bi.tch":1,
 "cra.p":1,
 "inanphuquy":1,
 "tockify.com":1,
 "Best SEO Solutions":1,
 "qiita":1,
 "̍|̎|̄|̅|̿|̑|̆|̐|͒|͗|͑|̇|̈|̊|͂|̓|̈́|͊|͋|͌|̃|̂|̌|͐|̀|́|̋|̏|̒|̓|̔|̽|̉|ͣ|ͤ|ͥ|ͦ|ͧ|ͨ|ͩ|ͪ|ͫ|ͬ|ͭ|ͮ|ͯ|̾|͛|͆|̚|̕|̛|̀|́|͘|̡|̢|̧|̨|̴|̵|̶|͏|͜|͝|͞|͟|͠|͢|̸|̷|͡|҉|̖|̗|̘|̙|̜|̝|̞|̟|̠|̤|̥|̦|̩|̪|̫|̬|̭|̮|̯|̰|̱|̲|̳|̹|̺|̻|̼|ͅ|͇|͈|͉|͍|͎|͓|͔|͕|͖|͙|͚|̣":1,
 "naughtyboy":1,
 "pofsex":1,
 "pofsex.com":1,
 "meetpof":1,
 "badoo":1,
 "xxvideo.com":1,
 "xxvideo":1,
 "Xhamster.com":1,
 "https://linktr.ee/":1,
 "julia.karandina":1,
 "https://linktr.ee/julia.karandina":1,
 "my username julia_sweety":1,
 "https://telegra.ph/Julia-Sweety-11-11":1,
 "/Julia-Sweety-11-11":1,
 "Julia-Sweety-":1,
 "https://telegra.ph/":1,
 "https://telegra.ph":1,
 "telegra.ph":1,
 "https://linktr.ee/-":1,
 "https://linktr.ee/-denis1714":1,
 "https://linktr.ee/-danis1714":1,
 "danis1714":1,
 "denis1714":1,
 "danis":1,
 "my username danis1714_danis1714":1,
 "my username_ danis1714":1,
 "@":1,
 "h.e.l.l.":1,
 "covid":1,
 "tiktok":1,
 "Tik Tok":1,
 "'''customer":1,
 "'''":1,
 "'''c":1,
 "Kartvally":1,
 "Mojofox":1,
 "Dailyknots":1,
 "...customer...":1,
 "Mozpassport.com":1,
 "MOZ":1,
 "meet.google.com":1,
 "meet.google":1,
 "padlet.com":1,
 "zoom.us":1,
 "docs.google.com":1,
 "google.com":1,
 "docs.google":1,
 "Edgenuity":1,
 "Apex":1,
 "edgenuity":1,
 "apex":1,
 "https://consumer.klickly.com":1,
 "klickly.com":1,
 "klickly":1,
 "sexx-chat.site":1,
 "sexxx-chat.site":1,
 "MASTERBATE":1,
 "sex-today.fun":1,
 "sexx-today.fun":1,
 "sexxx-today.fun":1,
 "MASTERBATION":1,
 "sex-chat":1,
 "sexx-chat":1,
 "sexxx-chat":1,
 "sex-partners.biz":1,
 "sex-partners":1,
 "sexxx-partners.biz":1,
 "sexx-partners.biz":1,
 "partners.biz":1,
 "sexyphotos.online":1,
 "gimkit.com":1,
 "GIMKIT":1,
 "po!rn":1,
 "Po!rn":1,
 "P1rn":1,
 "ROBLOX":1,
 "instagram":1,
 "Instagram":1,
 "h1rney":1,
 "h1rny":1,
 "Google":1,
 "skype":1,
 "HOMOPHOBIC":1,
 "homophobic":1,
 "N I G G E R":1,
 "chatt - sex.online":1,
 "chatt-sex.online":1,
 "sex.online":1,
 "chat-sex.online":1,
 "chattt - sex.online":1,
 "cuteladies.xyz":1,
 "WEBCAM":1,
 "WEB!CAM":1,
 "MAST!URB!ATE":1,
 "brainlygirls":1,
 "girls.online":1,
 ".online":1,
 "nu!de":1,
 "ba!be":1,
 "brainly.today":1,
 "NUD!E":1,
 "girlfriend":1,
 "boyfriend":1,
 "Hinge":1,
 "Tinder":1,
 "s e x":1,
 "chat":1,
 "dumb":1,
 "hacked":1,
 "google":1,
 "B R A I N LY. T O D A Y":1,
 "ʙʀᴀɪɴʟʏ.ᴛᴏᴅᴀʏ":1,
 "BRAINLY.TODAY":1,
 "Padlet":1,
 "padlet":1,
 "sexdates.fun":1,
 "www.sexdates.fun":1,
 "Fu*k me":1,
 "Fu*k":1,
 "fu*k":1,
 "www.caffeine.tv/Cheerqueenslove/broadcast":1,
 "www.caffeine.tv":1,
 "www.caffeine.tv/":1,
 "caffeine.tv":1,
 "caffeine.tv/":1,
 "youtubr":1,
 "TIK TOKS":1,
 "①|②|③|④|⑤|⑥|⑦|⑧|⑨|⑩|⑪|⑫|⑬|⑭|⑮|⑯|⑰|⑱|⑲|⑳|⑴|⑵|⑶|⑷|⑸|⑹|⑺|⑻|⑼|⑽|⑾|⑿|⒀|⒁|⒂|⒃|⒄|⒅|⒆|⒇|⒈|⒉|⒊|⒋|⒌|⒍|⒎|⒏|⒐|⒑|⒒|⒓|⒔|⒕|⒖|⒗|⒘|⒙|⒚|⒛|⒜|⒝|⒞|⒟|⒠|⒡|⒢|⒣|⒤|⒥|⒦|⒧|⒨|⒩|⒪|⒫|⒬|⒭|⒮|⒯|⒰|⒱|⒲|⒳|⒴|⒵|Ⓐ|Ⓑ|Ⓒ|Ⓓ|Ⓔ|Ⓕ|Ⓖ|Ⓗ|Ⓘ|Ⓙ|Ⓚ|Ⓛ|Ⓜ|Ⓝ|Ⓞ|Ⓟ|Ⓠ|Ⓡ|Ⓢ|Ⓣ|Ⓤ|Ⓥ|Ⓦ|Ⓧ|Ⓨ|Ⓩ|ⓐ|ⓑ|ⓒ|ⓓ|ⓔ|ⓕ|ⓖ|ⓗ|ⓘ|ⓙ|ⓚ|ⓛ|ⓜ|ⓝ|ⓞ|ⓟ":1,
 "ⓠ|ⓡ|ⓢ|ⓣ|ⓤ|ⓥ|ⓦ|ⓧ|ⓨ|ⓩ|⓪|⓫|⓬|⓭|⓮|⓯|⓰|⓱|⓲|⓳|⓴|⓵|⓶|⓷|⓸|⓹|⓺|⓻|⓼|⓽|⓾|⓿|㊲|㊳|㊴|㊵|㊶|㊷|㊸|㊹|㊺|㊻|㊼|㊽|㊾|㊿|㏠|㏡|㏢|㏣|㏤|㏥|㏦|㏧|㏨|㏩|㏪|㏫|㏬|㏭|㏮|㏯|㏰|㏱|㏲|㏳|㏴|㏵|㏶|㏷|㏸|㏹|㏺|㍘|㍙|㍚|㍛|㍜|㍝|㍞|㍟|㍠|㍡|㍢|㍣|㍤|㍥|㍦|㍧|㍨|㍩|㍪|㍫|㍬|㍭|㍮|㍯|㍰|０|１|２|３|４|５|６|７|８|９|Ａ|Ｂ|Ｃ|Ｄ|Ｅ|Ｆ|Ｇ|Ｈ|Ｉ|Ｊ|Ｋ|Ｌ|Ｍ|Ｎ|Ｏ|Ｐ|Ｑ|Ｒ|Ｓ|Ｔ":1,
 "Ｕ|Ｖ|Ｗ|Ｘ|Ｙ|Ｚ":1,
 "p*ssy":1,
 "p*ssy now":1,
 "www.sexnow.fun":1,
 "sexnow":1,
 "b11ty":1,
 "IDK":1,
 "idk":1,
 "bruh":1,
 "b11bies":1,
 "desmos.com":1,
 "p-u-s-s-y":1,
 "sëx cha.t":1,
 "sex chàt":1,
 "meetgooglecom/":1,
 "meetgooglecom":1,
 "̍|̎|̄|̅|̿|̑|̆|̐|͒|͗|͑|̇|̈|̊|͂|̓|̈́|͊|͋|͌|̃|̂|̌|͐|̀|́|̋|̏|̒|̓|̔|̽|̉|ͣ|ͤ|ͥ|ͦ|ͧ|ͨ|ͩ|ͪ|ͫ|ͬ|ͭ|ͮ|ͯ|̾|͛|͆|̚|̕|̛|̀|́|͘|̡|̢|̧|̨|̴|̵|̶|͏|͜|͝|͞|͟|͠|͢|̸|̷|͡|҉|̖|̗|̘|̙|̜|̝|̞|̟|̠|̤|̥|̦|̩|̪|̫|̬|̭|̮|̯|̰|̱|̲|̳|̹|̺|̻|̼|ͅ|͇|͈|͉|͍|͎|͓|͔|͕|͖|͙|͚|̣|๎|้":1,
 "nitrotype.com":1,
 "have zoom":1,
 "join zoom":1,
 "make a zoom":1,
 "open a zoom":1,
 "on zoom":1,
 "wanna zoom":1,
 "zoom code":1,
 "zoom me":1,
 "any girls wanna":1,
 "zoom call":1,
 "got a zoom":1,
 "want to zoom":1,
 "zoom app":1,
 "join to zoom":1,
 "join my zoom":1,
 "my zoom":1,
 "talk on zoom":1,
 "zoom meeting":1,
 "my zoòm":1,
 "start a zoom":1,
 "Zoom?":1,
 "down to zoom":1,
 "zoomm with":1,
 "in zoom":1,
 "zoom join":1,
 "google meet":1,
 "rate me":1,
 "watchparty.me":1,
 "follow my insta":1,
 "shut up":1,
 "bi.t.ch":1,
 "sh.i.t":1,
 "cutt.ly":1,
 "herecutt.ly":1,
 "cutt. ly":1,
 "dogmovie.net":1,
 "tinyurl.com":1,
 "linkcutter.ga":1,
 "yourlink.gg":1,
 "yourlink.gq/gyko":1,
 "shortlnk.ml":1,
 "cutlnk.ml":1,
 "tinylnk.ml":1,
 "shortlnk.gq":1,
 "tinylnk.gq":1,
 "heretnylnk.ml":1,
 "filetnylnk.ml":1,
 "belowtnylnk.ml":1,
 "tinyclick":1,
 "I can only upload it to a file hosting service":1,
 "you can download answer here":1,
 "answer is in a file":1,
 "customer care number":1,
 "i hate u":1,
 "b.o.o.b.s":1,
 "p.adlet":1,
 "pa.dlet":1,
 "padle.t":1,
 "zooom":1,
 "quizizz":1,
 "math papa":1,
 "bеlow!xtiny.cf":1,
 "sub to my":1,
 "yt channel":1,
 "follow me on insta":1,
 "add me on snap":1,
 "hot girls only":1,
 "im bored":1,
 "who wanna talk":1,
 "this isnt a school question":1,
 "friend zone":1,
 "Brainly mods":1,
 "anyone want to be my friend":1,
 "anyone want to be friends":1,
 "hunterxhunter":1,
 "wanna be friends":1,
 "who has discord":1,
 "zo.om":1,
 "zo-om":1,
 "kahoot":1,
 "what's your favorite":1,
 "finish the lyric":1,
 "finish the song":1,
 "filеxtiny":1,
 "xtiny":1,
 "Еxplаnаtiоn is in а filе":1,
 "BlTCH":1,
 "I uрlоаdеd thе аnswеr tо а filе hоsting":1,
 "Yоu cаn dоwnlоаd thе аnswеr hеrе":1,
 "Аnswеr is in а phоtо. I cаn оnly uplоаd it to a file hоsting sеrvice":1,
 ".tk":1,
 ".ga":1,
 ".cf":1,
 ".gq":1,
 "uplоаdеd it tо а filе hоsting":1,
 "quizlet.com":1,
 "4 sex":1,
 "zôom":1,
 "only girls zoom":1,
 "girls sex":1,
 "I don't know bro":1,
 "Herе's link tо thе аnswer":1,
 "Yоu cаn dоwnlоаd thе аnswеr":1,
 "girl sex":1,
 "I cоuldn't аttасh it hеrе, but I uplоаdеd it tо а filе hоsting.":1,
 "do a rp":1,
 "rp with me":1,
 "furry rp":1,
 "anime rp":1,
 "your fave":1,
 "just text me":1,
 "here's my number":1,
 "here's my email":1,
 "I do not know the answer to this question":1,
 "asdfghjkl":1,
 "bit․ly":1,
 "I uploadеd the answеr tо a filе hosting.":1,
 "for Interested girls":1,
 "zoo M id":1,
 "my insta is":1,
 "i am bored":1,
 "FREE POINTS":1,
 "cashapp":1,
 "cash app":1,
 "paypal":1,
 "im gay":1,
 "i'm gay":1,
 "bts stan":1,
 "who wants to talk":1,
 "pad/let":1,
 "cutt․ly":1,
 "Еxplаnаtiоn is in a filе":1,
 "rebrandly":1,
 "tinyurl":1,
 "bl.ink":1,
 "semrush":1,
 "ahrefs":1,
 "sniply":1,
 "parse.ly":1,
 "su.pr":1,
 "goo.gl":1,
 "is.gd":1,
 "snipurl":1,
 "tiny.cc":1,
 "fur.ly":1,
 "F R E E P O I N T S":1,
 "basesfile.com":1,
 "robux":1,
 "fortnite":1,
 "minecraft":1,
 "tik tok":1,
 "roblox":1,
 "name this song":1,
 "i'm bored":1,
 "NIGGA":1,
 "who do you simp for":1,
 "are you a simp":1,
 "i'm not a simp":1,
 "im not a simp":1,
 "smash or pass":1,
 "rate me 1":1,
 "The answer and explanation to your question in a file":1,
 "anyone wanna talk":1,
 "anyone wanna rp":1,
 "tnylnk":1,
 "cutlnk":1,
 "who wants to be friends":1,
 "se x y g i r l s":1,
 "come have f u n":1,
 "j oin f as t​":1,
 "customer /care/ number/":1,
 "*customer*care* number*":1,
 "shorturl":1,
 "deeznuts":1,
 "deeznutz":1,
 "E⁣xplanation i⁣s i⁣n a f⁣ile":1,
 "[tex]bit.^{}ly":1,
 "[tex]cutt.^{}ly":1,
 ".^{}tk":1,
 ".^{}ga":1,
 ".^{}cf":1,
 ".^{}gq":1,
 "[tex]basesfiles.^{}":1,
 "[tex]tnylnk.^{}":1,
 "[tex]cutlnk.^{}":1,
 "❤​":1,
 "u.to/":1,
 "I u⁣⁣ploaded t⁣⁣he a⁣⁣nswer t⁣⁣o a f⁣⁣ile h⁣⁣osting.":1,
 ".([tex].*[/tex])*l([tex].*[/tex])*y":1,
 ".([tex].*[/tex])*t([tex].*[/tex])*k":1,
 ".([tex].*[/tex])*c([tex].*[/tex])*f":1,
 ".([tex].*[/tex])*m([tex].*[/tex])*l":1,
 ".([tex].*[/tex])*g([tex].*[/tex])*a":1,
 ".([tex].*[/tex])*g([tex].*[/tex])*q":1,
 "fûçk":1,
 "fûçkèr":1,
 "dîçk":1,
 "fūčķěř":1,
 "u⁣⁣⁣ploaded i⁣⁣⁣t t⁣⁣⁣o a f⁣⁣⁣ile h⁣⁣⁣osting":1,
 "bit.[tex]^{}[/tex]ly/3a8Nt8n":1,
 "shorturl.at":1,
 "xtiny.cf":1,
 "tinylnk.cf":1,
 "tnylnk.gq":1,
 "xbox":1,
 "gamertag":1,
 "3a8Nt8n":1,
 "in a filebit":1,
 "I uploaded it to a file hosting":1,
 "Answer is in a photo":1,
 "3tZxaCQ":1,
 "bit.[tex]^{}[/tex]ly/3tZxaCQ":1,
 "Explanation is[tex]^{}[/tex] in a file":1,
 "You can download[tex]^{}[/tex] the answer":1,
 "I can only upload[tex]^{}[/tex] it to a file":1,
 "file hosting service. link":1,
 "Here's link[tex]^{}[/tex]":1,
 "photomath":1,
 "bad bvtch":1,
 "NlGGA":1,
 "1f3T96":1,
 "Answer:heyExplanation:":1,
 "Answer:hiExplanation:":1,
 "H⁣ere's li⁣nk t⁣o th⁣e answ⁣er:":1,
 "lm ao":1,
 "zoo.m":1,
 "h1t girls":1,
 "file host":1,
 "file hosting":1,
 "here's link":1,
 "bit.[tex]^{}[/tex]ly/3gVQKw3":1,
 "3gVQKw3":1,
 "filebit":1,
 "ly/3gVQKw3":1,
 "ly/3g":1,
 "herebit.":1,
 "[tex]^{}[/tex]":1,
 "I uploaded the answer to":1,
 "answer:bit.":1,
 "Link Below! bit.[tex]^{}[/tex]ly/":1,
 "prettygirls.website":1,
 "prettygirls website":1,
 "Photos of me getting fu!c!ke!d in the toilet at school watch here for free - : ₚᵣₑₜₜygᵢᵣₗₛ.wₑbₛᵢₜₑ":1,
 "fu!c!ke!d":1,
 "ₚᵣₑₜₜygᵢᵣₗₛ.wₑbₛᵢₜₑ":1,
 "Jaiminy`creation myshopify customer care number,9831336199®®®#":1,
 "jaiminy`creation myshopify customer care number,9831336199®®®#​`":1,
 "myshopify":1,
 "ꜱʜᴇ`ꜱ ɴᴜᴅᴇ ᴘʜᴏᴛᴏꜱ ᴀɴᴅ ᴠɪᴅꜱ ʜᴇʀᴇ ᴄᴏᴘʏ ᴛʜᴀᴛ ʟɪɴᴋ ᴀɴᴅ ᴏᴘᴇɴ ɪɴ ᴀ ɴᴇᴡ ᴛᴀʙ - ᵖʳᵉᵗᵗʸᵍⁱʳˡˢ.ʷᵉᵇˢⁱᵗᵉ":1,
 "prettygirls,website":1,
 "ꜱʜᴇ`ꜱ ɴᴜᴅᴇ ᴘʜᴏᴛᴏꜱ ᴀɴᴅ ᴠɪᴅꜱ ʜᴇʀᴇ ᴄᴏᴘʏ ᴛʜᴀᴛ ʟɪɴᴋ ᴀɴᴅ ᴏᴘᴇɴ ɪɴ ᴀ ɴᴇᴡ ᴛᴀʙ - ᵖʳᵉᵗᵗʸᵍⁱʳˡˢ.ʷᵉᵇˢⁱᵗᵉ`":1,
 "z.oo.m":1,
 "MY ɴᴜᴅᴇ ᴘʜᴏᴛᴏꜱ ᴀɴᴅ ᴠɪᴅꜱ ʜᴇʀᴇ ᴄᴏᴘʏ ᴛʜᴀᴛ ʟɪɴᴋ ᴀɴᴅ ᴏᴘᴇɴ ɪɴ ᴀ ɴᴇᴡ ᴛᴀʙ : ᵖʳᵉᵗᵗʸᵍⁱʳˡˢ.ʷᵉᵇˢⁱᵗᵉ":1,
 "fock":1,
 "foch":1,
 "zo om":1,
 "zo*om":1,
 "z.oom":1,
 "z oom":1,
 "z11m":1,
 "bítch":1,
 "Gauthmath":1,
 "msngr":1,
 "1X17dra":1,
 "i⁣s [tex]^{}[/tex]in the fil[tex]^{}[/tex]e below":1,
 "bit[tex]^{}[/tex].ly":1,
 "f(uck) sh!*t f.*ck":1,
 "jo in":1,
 "deez":1,
 "meet code":1,
 "meeting id":1,
 "gmeet":1,
 "Mee.tin.g I.D":1,
 "bit.[tex]^{}[/tex]ly":1,
 "fu!ck!ed":1,
 "www.nowdate.fun":1,
 "pu**y":1,
 "ᵂᵃⁱᵗⁱⁿᵍ":1,
 "ᴄｏᴍᴇ２ᴍᴇ":1,
 "ᵐʸ":1,
 "ｂｒａｉｎｌｙ.ｔｏｄａｙ":1,
 "ｗａｈｔ":1,
 "ｋｎｏｗ":1,
 "ｄｏ":1,
 "ʷᵉᵇᶜᵃᵐ":1,
 "ⁿᵃᵏᵉᵈ":1,
 "ˢᵖᵃᶜᵉ":1,
 "ᵇʳᵃⁱⁿˡʸᶜᵒᵐ":1,
 "ᴵᶠ":1,
 "ˢᵉᵉ":1,
 "ʷᵃⁿᵗ":1,
 "ᴰᵒ":1,
 "ᵇᵒᵒᵇˢ":1,
 "ᶠᵒʳ":1,
 "peynicumrei1985":1,
 "ᵘˢᵉ":1,
 "wealthtertentkin1981":1,
 "ʸᵒᵘʳ":1,
 "ʷᵒʳʳʸ":1,
 "ᴰᵒⁿᵗ":1,
 "ᶠʳᵉᵉ":1,
 "ⁱᵗˢ":1,
 "ʷⁱᵗʰ":1,
 "ᵐᵃˢᵗᵘʳᵇᵃᵗᵉ":1,
 "ᴵ":1,
 "suicidal":1,
 "ˢᵉˣʸᵖʰᵒᵗᵒˢ":1,
 "ʸᵒᵘ":1,
 "chatt":1,
 "ᵒⁿˡⁱⁿᵉ":1,
 "ᵃ":1,
 "privovediz1985":1,
 "ｆｏｒ":1,
 "ｙｏｕ":1,
 "ᵍⁱʳˡ":1,
 "abofimov1986":1,
 "ʳᵉᵃˡˡʸ":1,
 "ᵈⁱᶜᵏ":1,
 "ᵐᵒᵘᵗʰ":1,
 "ᵇᵃᵈ":1,
 "s-tupid":1,
 "ᴾᵘⁿⁱˢʰ":1,
 "ʷᵃˢ":1,
 "ⁱⁿ":1,
 "ᴵᵐ":1,
 "henquismarim1981":1,
 "ᵐᵉ":1,
 "sex-today":1,
 "ᵒⁿ":1,
 "ｈｅｒｅ":1,
 "di.ck":1,
 "ᵇʳᵃⁱⁿˡʸ.ᵗᵒᵈᵃʸ":1,
 "look!":1,
 "mmmmm":1,
 "ｔｏ":1,
 "s*x":1,
 "bit-ch":1,
 "a-s-s":1,
 "senpai":1,
 "n-i-g-g-e-r":1,
 "ˡⁱⁿᵏ":1,
 "swat":1,
 "a//ss":1,
 "ᶠⁱⁿᵈ":1,
 "ʰᵉʳᵉ":1,
 "fu*cking":1,
 "dadyy":1,
 "a/ss":1,
 "thorght":1,
 "afro":1,
 "duk":1,
 "ⓦⓐⓝⓣ":1,
 "gayyyy":1,
 "ｇｏ":1,
 "ⓨⓞⓤ":1,
 "virgin":1,
 "shid":1,
 "ａｎｄ":1,
 "ｔｈｅ":1,
 "ⓢⓔⓔ":1,
 "d*ck":1,
 "busty":1,
 "shlt":1,
 "ⓝⓐⓚⓔⓓ":1,
 "as.s":1,
 "fu-ck":1,
 "cn":1,
 "virginity":1,
 "fu.cking":1,
 "msg":1,
 "ƒuçk":1,
 "sucked!":1,
 "fucing":1,
 "j1in":1,
 "fu*ck":1,
 "someb!ody":1,
 "drunk":1,
 "naked":1,
 "a/s/s":1,
 "babes":1,
 "sexx":1,
 "peen":1,
 "fu.ck.ing":1,
 "h.o.e":1,
 "stu*pid":1,
 "asss":1,
 "a.ss":1,
 "åšš":1,
 "ⓜⓔ":1,
 "niger":1,
 "aroused":1,
 "bit.ch":1,
 "f**":1,
 "f#ck":1,
 "pull-out":1,
 "i,m":1,
 "p****":1,
 "sucked":1,
 "cuhh":1,
 "n.ggas":1,
 "glock":1,
 "pusi":1,
 "me!?!":1,
 "bi-tch":1,
 "sh-it":1,
 "(shut":1,
 "☺":1,
 "flirt":1,
 "obb-ovjk-adtjoin":1,
 "penes":1,
 "a*s":1,
 "ni-gga":1,
 "guidelines":1,
 "panty":1,
 "smexy":1,
 "fūcking":1,
 "nggaz":1,
 "di-ck":1,
 "fu..ck":1,
 "b**ch":1,
 "whooped":1,
 "fu.cked":1,
 "b-i-t-c-h":1,
 "dicks":1,
 "shi.t":1,
 "ngga":1,
 "homie":1,
 "juicy":1,
 "g11gle":1,
 "assss":1,
 "p***":1,
 "luv":1,
 "ಥ_ಥ":1,
 "boutta":1,
 "(yeah)":1,
 "ayy":1,
 "hiii":1,
 "sh.it":1,
 "ᵇᵉ":1,
 "junkie.....me":1,
 "ｉｔ":1,
 "lookin'":1,
 "shorty":1,
 "pad.let":1,
 "∴":1,
 "a**":1,
 "seks!-!ch!at":1,
 "homophobes":1,
 "a.s.s":1,
 "karens":1,
 "actin'":1,
 "butthole":1,
 "f*":1,
 "keyonn":1,
 "cha.t":1,
 "ᵃⁿᵈ":1,
 "bick":1,
 "as.f":1,
 "ᵗʰᵉ":1,
 "fkn":1,
 "bullsh*t":1,
 "mtf":1,
 "n.gga":1,
 "thicc":1,
 "ʷᵒⁿᵗ":1,
 "ˢᵒʳʳʸ":1,
 "ᶠᵒˡˡᵒʷ":1,
 "ᵒⁿˡʸ":1,
 "ᵀᵒᵖ":1,
 "ˢⁱᵗᵉ":1,
 "ᵇᵘʳⁿʸ":1,
 "ᵗʰⁱˢ":1,
 "ᶜʰⁱᶜᵏˢ":1,
 "ᵇᵘˢᵗʸ":1,
 "****":1,
 "masturbation":1,
 "yuh":1,
 "fk":1,
 "keyonnn":1,
 "echo1155":1,
 "europa1433":1,
 "lemme":1,
 "trynna":1,
 "shawty":1,
 "shii":1,
 "finna":1,
 "tryna":1,
 "wanna":1,
 "An y g irl":1,
 "s ex and":1,
 "like s ex":1,
 "wan t to do":1,
 "twitter":1,
 "Inst'agram":1,
 "Snapch'at":1,
 "Hey Friend":1,
 "❤":1,
 "(◍•ᴗ•◍)":1,
 "looking for friends":1,
 "looking for some friends":1,
 "my user is":1,
 "my username is":1,
 "An y g ir":1,
 "g ir l":1,
 "l ike sx":1,
 "w an t to do":1,
 "wh o l ike":1,
 "Heyy guys":1,
 "anyone want to be my":1,
 "Any girl":1,
 "on snap":1,
 "snap me":1,
 "Annnyy":1,
 "girlllllll":1,
 "wannt":1,
 "dirrrtttyyy":1,
 "chttttt":1,
 "z oo omm​":1,
 "dirty chat":1,
 "ta..lk":1,
 "he..lla":1,
 "bo*red​":1,
 "gírl":1,
 "Mastûrbate":1,
 "are you a girl":1,
 "are you a boy":1,
 "r u a girl":1,
 "r u a boy":1,
 "are u a girl":1,
 "are u a boy":1,
 "r you a girl":1,
 "r you a boy":1,
 "gí4l":1,
 "Mastûrbaté":1,
 "cutt[tex]^{}[/tex].ly":1,
 "4Rq[tex]^{}[/tex]tIvk":1,
 "cutt[tex]^{}[/tex]":1,
 "cutt":1,
 "Explanation is[tex]^{}[/tex]":1,
 "[tex]^{}[/tex] in a file":1,
 "You can down[tex]^{}[/tex]load":1,
 "down[tex]^{}[/tex]load":1,
 "load the answer":1,
 "Li[tex]^{}[/tex]nk below!":1,
 "Here's li[tex]^{}[/tex]nk":1,
 "li[tex]^{}[/tex]nk":1,
 "b-ored":1,
 "Timed Test":1,
 "Ra.te me ig bc im bo.red":1,
 "Ra.te me":1,
 "im bo.red":1,
 "Hey Anyone wann.a be friends":1,
 "❁◕ ‿ ◕❁":1,
 "love u":1,
 "join for talk​":1,
 "plz join":1,
 "Anyone here is on?":1,
 "Want to have someone to talk to":1,
 "sugar daddy":1,
 "sugar baby":1,
 "sugar mommy":1,
 "sugar mama":1,
 "trump 1111":1,
 "(╥﹏╥)":1,
 "plz":1,
 "just want to text":1,
 "can i give you my #":1,
 "can i give u my #":1,
 "can you give me your #":1,
 "can u give me your #":1,
 "can u give me ur #":1,
 "can you give me ur #":1,
 "can you share your #":1,
 "can u share your #":1,
 "can u share ur #":1,
 "can you share ur #":1,
 "can i get ur #":1,
 "can i get your #":1,
 "^{}":1,
 "mdaf":1,
 "/bfuck/b":1,
 "/bc.k.":1,
 "fvch":1,
 "$:€X":1,
 "/bsex":1,
 "Pls dont report":1,
 "Anyone need a friend or someone to talk to?":1,
 "Anyone need a friend or someone to talk to":1,
 "Anyone need a friend":1
}
}
